<?php

namespace Utilisateurs\UtilisateursBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VillesRepository extends EntityRepository
{

  public function getVilles(){

    $qb = $this->createQueryBuilder('u')
      ->select('u')



      ->setMaxResults(500)
       ;
      return $qb->getQuery()->getResult();
  }
}
