admin_categories:
    pattern:  /
    defaults: { _controller: "EcommerceBundle:CategoriesAdmin:index" }

admin_categories_sort:
    pattern:  /{field}/{type}/sort
    defaults: { _controller: "EcommerceBundle:CategoriesAdmin:sort" }
    requirements: { type: ASC|DESC }

admin_categories_show:
    pattern:  /{id}/show
    defaults: { _controller: "EcommerceBundle:CategoriesAdmin:show" }

admin_categories_new:
    pattern:  /new
    defaults: { _controller: "EcommerceBundle:CategoriesAdmin:new" }

admin_categories_create:
    pattern:  /create
    defaults: { _controller: "EcommerceBundle:CategoriesAdmin:create" }
    requirements: { _method: post }

admin_categories_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EcommerceBundle:CategoriesAdmin:edit" }

admin_categories_update:
    pattern:  /{id}/update
    defaults: { _controller: "EcommerceBundle:CategoriesAdmin:update" }
    requirements: { _method: post|put }

admin_categories_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EcommerceBundle:CategoriesAdmin:delete" }
    requirements: { _method: post|delete }
